// Generated by dts-bundle-generator v9.5.1

/**
 * The result of the solver function.
 */
export interface SolverResult {
  /** True if the puzzle is solved. */
  solved: boolean;
  /** The solution of the puzzle. */
  solution?: Puzzle;
  /**
   * All intermediate state of the puzzle during the solving process.
   */
  steps?: Puzzle[];
  /** List of all solutions if the puzzle has multiple solutions. */
  multipleSolutions?: Set<string>;
}
/** Alias for Puzzle */
export type Puzzle = string[][];
/**
 * Solves the bridges puzzle.
 * @param bridgesPuzzle A 2D matrix representing the puzzle where zeros represent empty spaces.
 * @param depth The recursion depth of the algorithm. Default value is 2.
 * @param checkForMultipleSolutions Whether to check for multiple solutions. Default value is false.
 * This option can be time intensive when set to true.
 */
export declare function solver(
  bridgesPuzzle: number[][],
  depth?: number,
  checkForMultipleSolutions?: boolean,
): SolverResult;

export {};
